
---
resources:
- name: source
  type: git
  source:
    uri: https://github.com/gadieichhorn/vertx-concourse-gradle.git
    branch: master
# - name: timer
#   type: time
#   source:
#     interval: 1m

jobs:
- name: gradle
  public: true
  plan:
  - get: source
    trigger: true
  - task: gradle
    file: source/ci/gradle.yml
  - task: docker
    file: source/ci/docker.yml
