
---
resources:
- name: source
  type: git
  source:
    uri: https://github.com/gadieichhorn/vertx-concourse-gradle.git
- name: timer
  type: time
  source:
    interval: 2m

jobs:
- name: vertx-gradle
  public: true
  plan:
  - get: source
  - get: timer
    trigger: true
  - task: hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: gradle, tag: 3.5-jdk-alpine}
      inputs:
      - name: source
      run:
        path: source/vertx-concourse-gradle/ci/task-build.sh
