
---
resources:
- name: source
  type: git
  source:
    uri: https://github.com/gadieichhorn/vertx-concourse-gradle.git
    branch: master
- name: timer
  type: time
  source:
    interval: 1m

jobs:
- name: vertx-gradle
  public: true
  plan:
  - get: source
  - get: timer
    trigger: true
  - task: gradle-build
    file: source/ci/build.yml
  - task: docker-build
    file: source/ci/docker.yml
