
---
resources:
- name: source
  type: git
  source:
    uri: https://github.com/alexlehm/vertx-concourse-gradle.git
    branch: master
- name: docker
  type: docker-image

jobs:
- name: gradle
  public: true
  plan:
  - get: source
    trigger: true
  - task: gradle
    file: source/ci/gradle.yml
    output: source/build
  - task: docker
    input: source/docker/build
    params:
      build: source/docker
    file: source/ci/docker.yml
